global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "trading_alerts.yml"

scrape_configs:
  # PostgreSQL metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 5s
    metrics_path: /metrics
    
  # Redis metrics  
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 5s
    
  # PgBouncer metrics
  - job_name: 'pgbouncer-exporter'
    static_configs:
      - targets: ['pgbouncer-exporter:9127']
    scrape_interval: 10s
    
  # Application metrics (when you add your trading app)
  - job_name: 'trading-app'
    static_configs:
      - targets: ['trading-app:8080']
    scrape_interval: 5s
    metrics_path: /metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Trading-specific recording rules
recording_rules:
  - name: "trading_performance"
    rules:
      - record: "trading:order_rate_5m"
        expr: "rate(postgres_stat_user_tables_n_tup_ins{table='orders'}[5m])"
        
      - record: "trading:trade_rate_5m" 
        expr: "rate(postgres_stat_user_tables_n_tup_ins{table='trades'}[5m])"
        
      - record: "trading:db_connections_utilization"
        expr: "postgres_stat_activity_count / postgres_settings_max_connections"
        
      - record: "trading:response_time_95p"
        expr: "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))"